development:
  bucket: dev.example.com
  access_key_id: ACCESS_KEY_ID
  secret_access_key: SECRET_ACCESS_KEY

test:
  bucket: test.example.com
  access_key_id: ACCESS_KEY_ID
  secret_access_key: SECRET_ACCESS_KEY

production:
  bucket: live.example.com  
  access_key_id: ACCESS_KEY_ID
  secret_access_key: SECRET_ACCESS_KEY