development:
  bucket: dev-martinfurniture
  aws_access_key_id: AKIAJFINSTYH5U6JVWCA
  aws_secret_access_key: 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

test:
  bucket: test-martinfurniture
  aws_access_key_id: AKIAJFINSTYH5U6JVWCA
  aws_secret_access_key: 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

production:
  bucket: live-martinfurniture
  aws_access_key_id: AKIAJFINSTYH5U6JVWCA
  aws_secret_access_key: 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