development:
  bucket: dev.martinfurniture.com
  access_key_id: AKIAJFINSTYH5U6JVWCA
  secret_access_key: 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

test:
  bucket: test.martinfurniture.com
  access_key_id: AKIAJFINSTYH5U6JVWCA
  secret_access_key: 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

production:
  bucket: live.martinfurniture.com
  access_key_id: AKIAJFINSTYH5U6JVWCA
  secret_access_key: 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